### PR TITLE
Update for CUDA 12.4.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/17

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by jakirkham** [comment]
Azure didn't run on `main`. Started [a new Azure run]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=890132&view=results ). Should upload packages in a bit

**Comment by jakirkham** [comment]
Azure run completed. Packages are uploaded. May still be mirroring to CDN

**Pull request merged**
